package_dir: "/output"
prelude:
- git clone --depth 1 --branch master https://invent.kde.org/maui/mauiman.git
- |
  mkdir -p mauiman/build && cd mauiman/build && \
  cmake \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DENABLE_BSYMBOLICFUNCTIONS=OFF \
      -DQUICK_COMPILER=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_SYSCONFDIR=/etc \
      -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
      -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON \
      -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON \
      -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" \
      -DCMAKE_VERBOSE_MAKEFILE=ON \
      -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu ../ && make && make install
- git clone https://github.com/KDE/mauikit.git
- |
   cd mauikit && git checkout "{{.Values.maui_kit_commit}}" -b build && \
   cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib && make && make install

- git clone https://invent.kde.org/maui/mauikit-filebrowsing.git
- |
   cd mauikit-filebrowsing && git checkout "{{.Values.maui_kit_filebrowsing_commit}}" -b build && \
   mkdir -p build
- |
  cd mauikit-filebrowsing/build && \
  cmake \
   -DCMAKE_INSTALL_PREFIX=/usr \
   -DENABLE_BSYMBOLICFUNCTIONS=OFF \
   -DQUICK_COMPILER=ON \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_SYSCONFDIR=/etc \
   -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
   -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON \
   -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON \
   -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" \
   -DCMAKE_VERBOSE_MAKEFILE=ON \
   -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/MauiKit .. && make && make install

- |
   git clone https://github.com/Nitrux/maui-shell.git && cd maui-shell && \
   git checkout "{{.Values.maui_shell_commit}}" -b build
-  |
   mkdir -p maui-shell/build && cd maui-shell/build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BSYMBOLICFUNCTIONS=OFF -DQUICK_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu .. && \
   make && make install
steps:
- cd mauikit && make DESTDIR="/output" install
- cd mauikit-filebrowsing/build && make DESTDIR="/output" install
- cd maui-shell/build && make DESTDIR="/output" install
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
excludes:
{{ template "portage_excludes" }}
