excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "apps"
  name: "nodejs"
  version: ">=0"
