excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "java"
  version: ">=0"
