excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "vhba-lts"
  version: ">=0"
requires_final_images: true
