excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}

prelude:
- cp -rf package.use /etc/portage/
- cp -rf patches /etc/portage/

steps:
- USE="-cairo -harfbuzz" emerge -1 media-libs/harfbuzz media-libs/freetype
- USE="-vaapi" emerge -1 media-libs/mesa
- emerge -1 dev-tex/bibtexu gst-plugins-base media-plugins/gst-plugins-pulse
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
- cp -rv xorg.conf.d/ /etc/X11/
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
- category: "layers"
  name: "sys-fs"
  version: ">=0"
- category: "layers"
  name: "codecs"
  version: ">=0"
