excludes:
- ^/etc/sasl2/sasldb2
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf patches /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.env /etc/portage/
- emerge -1 app-arch/rpm2targz dev-lang/rust-bin virtual/rust app-text/docbook-xsl-ns-stylesheets
steps:
- USE="-cairo -harfbuzz" emerge -1 -j ${JOBS} media-libs/harfbuzz media-libs/freetype
- USE="-vaapi" emerge -1 -j ${JOBS} media-libs/mesa
- emerge -1 -j ${JOBS} dev-tex/bibtexu gst-plugins-base media-plugins/gst-plugins-pulse
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
- cp -rv xorg.conf.d/ /etc/X11/
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
- category: "layers-buildbase"
  name: "sys-fs"
  version: ">=0"
- category: "layers-buildbase"
  name: "net-tools"
  version: ">=0"
- category: "layers-buildbase"
  name: "codecs"
  version: ">=0"
requires_final_images: true
