excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- mkdir -p /var/db/repos/gentoo/x11-themes/mint-icons && cp ebuilds/mint-icons-1.7.5.ebuild /var/db/repos/gentoo/x11-themes/mint-icons
- ebuild /var/db/repos/gentoo/x11-themes/mint-icons/mint-icons-1.7.5.ebuild manifest
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "X"
  version: ">=0"
