excludes:
{{ template "portage_excludes" }}
- ^/usr/share/applications/org.gnome.Vte.App.Gtk3.desktop
- ^/usr/share/applications/org.gnome.Vte.App.Gtk4.desktop
env:
{{ template "portage_env" . }}
prelude:
# Needed for old spidermonkey ( used in layers/mate and layers/cinnamon )
- EMERGE_DEFAULT_OPTS="--getbinpkg" emerge -1 llvm-core/clang:19 llvm-core/lld:19 llvm-core/llvm:19
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
# cleanup ccache
- CCACHE_DIR=/var/cache/ccache/ ccache -C
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true