excludes:
{{ template "portage_excludes" }}
- ^/run
- ^/etc/openldap/ssl/ldap.*
- ^/etc/sasl2/sasldb2
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- cp -rf patches /etc/portage/
# rust-bin here
- USE="inspector profiler rustfmt" emerge -1 dev-lang/rust-bin
- emerge -1 dev-util/cmake sys-devel/bison app-alternatives/yacc
- emerge dev-util/ccache
- emerge app-portage/gentoolkit
- echo "dev-python/pillow -jpeg -tiff" >> /etc/portage/package.use/temp.use
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
# Workaround 2025-12-31: There seems to be a bug in the dev-libs/libmbim ebuild. We must make sure dev-perl/Locale-gettext is installed before dev-libs/libmbim gets merged.
- emerge -1 dev-perl/Locale-gettext
{{ template "portage_build_gentoo_binary" . }}
# Clean up build dependencies
- emerge -C dev-python/pillow dev-python/docutils dev-python/sphinx dev-python/sphinx-rtd-theme
- emerge --depclean
# Clean up binary cache (we are not using the template for binaries
- if [ -d /var/cache/binpkgs/ ] && [ ! -z "$(ls -A /var/cache/binpkgs/)" ]; then rm -r /var/cache/binpkgs/*; fi
- rm /etc/portage/package.use/temp.use
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
