excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
# handle LDFLAGS muffin bug (added 2026-04-24)
- echo 'LDFLAGS="${LDFLAGS} -Wl,-rpath=/usr/lib64/muffin"' > /etc/portage/env/muffin-rpath.conf
- echo "x11-wm/muffin muffin-rpath.conf" >> /etc/portage/package.env
# end muffin LDFLAGS bug
- emerge -1 app-eselect/eselect-repository
- eselect repository enable haarp
- emaint sync -r haarp
- eselect repository enable binaryden
- emaint sync -r binaryden
- eselect repository add mocaccino-overlay git https://codeberg.org/MocaccinoOS/mocaccino-overlay.git
- emaint sync -r mocaccino-overlay
# Remove broken src_prepare
- sed -i '/^src_prepare()/,/^}/d' /var/db/repos/binaryden/media-gfx/xviewer/xviewer-3.4.16.ebuild
- ebuild /var/db/repos/binaryden/media-gfx/xviewer/xviewer-3.4.16.ebuild manifest
# Add custom ebuild for cinnamon-spices-extensions
- mkdir -p /var/db/repos/gentoo/gnome-extra/cinnamon-spices-extensions && cp ebuilds/cinnamon-spices-extensions-9999.ebuild /var/db/repos/gentoo/gnome-extra/cinnamon-spices-extensions/cinnamon-spices-extensions-9999.ebuild
- ebuild /var/db/repos/gentoo/gnome-extra/cinnamon-spices-extensions/cinnamon-spices-extensions-9999.ebuild manifest
- emerge -1 x11-themes/gnome-themes-standard x11-themes/adwaita-icon-theme
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
- eselect repository remove binaryden
- eselect repository remove haarp
- eselect repository remove mocaccino-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
