excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
# install 
- cp -rf env /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
