requires:
- category: "layers"
  name: "gentoo-portage"
  version: ">=0"
unpack: true
env:
{{ template "portage_env" . }}

prelude:
- cp -rf package.use /etc/portage/
- cp -rf profile /etc/portage/
- cp -rf make.conf /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf patches/ /etc/portage/
- cp -rf bashrc /etc/portage/
- cp -rf env /etc/portage/
- cp -rf package.env /etc/portage/
steps:
# prevent softblock, see https://bugs.gentoo.org/831980
- emerge -1 sys-apps/shadow sys-apps/util-linux
- emerge -1 dev-lang/rust-bin virtual/rust
- emerge -1 sys-apps/systemd
- emerge -1 dev-libs/openssl net-misc/openssh net-misc/curl net-dns/unbound
- emerge -1uDN @system -j $JOBS
- emerge -uDN --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
{{ template "portage_build" . }}
- chmod -R 0700 /{etc,usr/share}/polkit-1/rules.d
- chown -R 102:0 /{etc,usr/share}/polkit-1/rules.d
- emerge -C app-eselect/eselect-rust virtual/rust dev-lang/rust-bin dev-lang/yasm dev-lang/python:3.10
excludes:
- ^/dev
- ^/etc/._cfg.*
- ^/etc/environment.d/10-gentoo-env.conf
- ^/etc/unbound/unbound_*
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/etc/udev/hwdb.bin
- ^/etc/ld.so.cache
- ^/etc/localtime
- ^/etc/profile.env
- ^/etc/csh.env
- ^/etc/subgid
- ^/etc/subuid
- ^/mnt/.keep
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
- ^/run
- ^/sys
- ^/tmp/tree.tar.tgz
- ^/proc
- ^/luetbuild

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc.*
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.gcc_version}}/libstdc\+\+.so.*
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.gcc_version}}/32/libstdc\+\+.so.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

{{ template "portage_excludes" }}

# Emerge/portage
- ^/usr/bin/emerge
- ^/usr/bin/emerge-webrsync
- ^/usr/sbin/dispatch-conf
- ^/etc/dispatch-conf.conf
- ^/usr/lib/python-exec/python.*/dispatch-conf
- ^/usr/share/man/man1/dispatch-conf.1.bz2
- ^/usr/share/man/man1/emerge.1.bz2

# We still depend on env-update
# - ^/usr/lib/python-exec/python.*/emerge/.*
# - ^/usr/lib/python.*/site-packages/portage
# - ^/usr/lib/python.*/site-packages/_emerge
# - ^/usr/lib/python.*/site-packages/_emerge/.*
# - ^/usr/lib/python.*/site-packages/portage/.*

# - ^/usr/share/man/man3/sd_event_dispatch.3
# - ^/usr/lib/portage/.*
