requires:
- category: "layers"
  name: "gentoo-portage"
  version: ">=0"
unpack: true
env:
{{ template "portage_env" . }}
- MAKEOPTS="--jobs 24 --load-average 25"
prelude:
# Install our kernel-tuning-file
- cp mocaccino-kernel-tuning/70-mocaccino.conf /usr/lib/sysctl.d/70-mocaccino.conf
{{ template "portage_copy_package_files" . }}
- cp -rf profile patches bashrc env /etc/portage/
{{ if ne .Values.arch "amd64" }}
- cp -rf make.conf.{{.Values.arch}} /etc/portage/make.conf
{{ else }}
- cp -rf make.conf /etc/portage/
{{ end }}
# temp use flags required for pillow. We drop this later
- echo "dev-python/pillow -jpeg -tiff" >> /etc/portage/package.use/temp.use
# temp mask for debugging
- echo "media-libs/mesa" >> /etc/portage/package.mask/temp.mask
# rebuild perl packages
- emerge -1av $(qlist -IC 'perl-core' 'virtual/perl-*' 'dev-perl/*')
# avoid circular deps
- USE="-http2 -http3 -quic -curl_quic_openssl" emerge -1 net-misc/curl
# required for binary packages
- cp -rf binrepos.conf /etc/portage/
- emerge -1 app-portage/getuto && getuto
steps:
- FEATURES="noinfo nodoc -preserve-libs -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox binpkg-request-signature" emerge -1uDN @system -j $JOBS
- FEATURES="noinfo nodoc -preserve-libs -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox binpkg-request-signature" emerge -uDN --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
{{ template "portage_build_gentoo_binary" . }}
- chmod -R 0700 /usr/share/polkit-1/rules.d && chown -R 102:0 /usr/share/polkit-1/rules.d
# Switch iptables to the modern nftables backend (avoids legacy xtables-compat mode)
- eselect iptables set xtables-nft-multi
# Clean up build deps
- emerge -C app-text/po4a dev-lang/yasm dev-python/docutils dev-python/pillow dev-util/gdbus-codegen dev-util/gperf sys-apps/help2man app-text/docbook-xml-dtd app-text/asciidoc app-text/xmlto app-text/docbook-xsl-ns-stylesheets app-text/docbook-xsl-stylesheets
# Remove Meson here
- emerge -C dev-build/meson dev-build/meson-format-array dev-python/meson-python
- emerge --depclean
# Clean up binary cache (we are not using the template for binaries
- if [ -d /var/cache/binpkgs/ ] && [ ! -z "$(ls -A /var/cache/binpkgs/)" ]; then rm -r /var/cache/binpkgs/*; fi
- rm /etc/portage/package.use/temp.use
- rm /etc/portage/package.mask/temp.mask
excludes:
- ^/dev
- ^/etc/._cfg.*
- ^/etc/environment.d/10-gentoo-env.conf
- ^/etc/unbound/unbound_*
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/portage
- ^/etc/machineid
- ^/etc/udev/hwdb.bin
- ^/etc/ld.so.cache
- ^/etc/localtime
- ^/etc/profile.env
- ^/etc/csh.env
- ^/etc/subgid
- ^/etc/subuid
- ^/mnt/.keep
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/run
- ^/sys
- ^/tmp/tree.tar.tgz
- ^/proc
- ^/luetbuild
- ^/usr/portage
- ^/usr/lib/python{{.Values.python_version}}/test

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc.*
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.gcc_version}}/libstdc\+\+.so.*
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.gcc_version}}/32/libstdc\+\+.so.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

{{ template "portage_excludes" }}

# Emerge/portage
- ^/usr/bin/emerge
- ^/usr/bin/emerge-webrsync
- ^/usr/sbin/dispatch-conf
- ^/etc/dispatch-conf.conf
- ^/usr/lib/python-exec/python.*/dispatch-conf
- ^/usr/share/man/man1/dispatch-conf.1.bz2
- ^/usr/share/man/man1/emerge.1.bz2

# We still depend on env-update
# - ^/usr/lib/python-exec/python.*/emerge/.*
# - ^/usr/lib/python.*/site-packages/portage
# - ^/usr/lib/python.*/site-packages/_emerge
# - ^/usr/lib/python.*/site-packages/_emerge/.*
# - ^/usr/lib/python.*/site-packages/portage/.*

# - ^/usr/share/man/man3/sd_event_dispatch.3
# - ^/usr/lib/portage/.*
