excludes:
{{ template "portage_excludes" }}
#TODO: Why is this service file here?
- ^/usr/lib/systemd/system/pam_namespace.service
env:
{{ template "portage_env" . }}
prelude:
- echo 'CONFIG_PROTECT_MASK="/etc/libvirt/nwfilter"' > /etc/portage/env/libvirt.env
- echo 'app-emulation/libvirt libvirt.env' >> /etc/portage/package.env
{{ template "portage_copy_package_files" . }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable nest
- emaint sync -r nest
- USE="-smartcard" emerge app-emulation/spice
{{ template "portage_prelude_build" . }}
steps:
- USE="-smartcard" emerge app-emulation/spice
{{ template "portage_build" . }}
- eselect repository remove nest
- emerge -C app-eselect/eselect-repository
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
