excludes:
{{ template "portage_excludes" }}

env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
# We need this in env.d until this is in stable tree. See https://bugs.gentoo.org/832773
- echo "LDPATH=/usr/lib64/Imath-3" > /etc/env.d/99imath
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
