image: "alpine"
package_dir: "/package"
prelude:
- apk update && apk add imagemagick && apk add git
- git clone https://github.com/joostruis/luet_pm_gui.git
- cd luet_pm_gui && chmod +x install.sh && ./install.sh
steps:
- for size in 16 24 32 48 64 128 256; do mkdir -p /package/usr/share/icons/hicolor/"${size}x${size}"/apps && magick /package/usr/share/pixmaps/vajo.png -resize "${size}x${size}" /package/usr/share/icons/hicolor/"${size}x${size}"/apps/vajo.png; done