image: "alpine"

prelude:
- apk add git bash
- git clone https://github.com/vinceliuice/Tela-icon-theme.git
- cd Tela-icon-theme && git checkout "a0697e3277eb49818d739a50c35d2561306423ef" -b build
steps:
- echo '#!/bin/sh' > /usr/bin/gtk-update-icon-cache
- chmod +x /usr/bin/gtk-update-icon-cache
- cd Tela-icon-theme && ./install.sh -d /usr/share/icons
includes:
- /usr/share/icons*
