excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 app-eselect/eselect-repository
# An unofficial 'hyproverlay' repository has been created at
#  https://codeberg.org/hyproverlay/hyproverlay.git
# for communal maintenance of these packages as well as several new
# (unpackaged in ::gentoo) dependencies.
- eselect repository enable hyproverlay
- emaint sync -r hyproverlay
# needed for clipman
- eselect repository enable guru
- emaint sync -r guru
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove guru hyproverlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
