excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
