excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
# See upstream bug: https://bugs.gentoo.org/864981
# See https://github.com/mocaccinoOS/mocaccino/issues/195
- sed -i 's|/73361/|/77450/|' /var/db/repos/gentoo/media-fonts/vlgothic/vlgothic-20200720.ebuild
- ebuild /var/db/repos/gentoo/media-fonts/vlgothic/vlgothic-20200720.ebuild manifest
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "X"
  version: ">=0"