image: "quay.io/mocaccino/micro:master"

package_dir: /mocaccino-dracut
steps:
- |
   mkdir -p /{{ .Values.name }}/usr/bin && \
   cp -rfv mocaccino-dracut  /{{ .Values.name }}/usr/bin/ && \
   chmod +x /{{ .Values.name }}/usr/bin/mocaccino-dracut && \
   mkdir -p /{{ .Values.name }}/etc/dracut.conf.d/ && \
   cp mocaccino.conf /{{ .Values.name }}/etc/dracut.conf.d/99-mocaccino.conf && \
   cp compression.conf /{{ .Values.name }}/etc/dracut.conf.d/compression.conf
