excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
