excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}

prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
# Temporary fix for fprintf
- sed -i /lib/systemd/system/fprintd.service -e 's|^ReadWritePaths.*|ReadWritePaths=/var/lib/fprint|'
requires:
- category: "layers"
  name: "X"
  version: ">=0"
- category: "layers"
  name: "gnome-common"
  version: ">=0"
