excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build" . }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable gentoo-zh
- emaint sync -r gentoo-zh
steps:
{{ template "portage_build" . }}
- eselect repository remove gentoo-zh
- emerge -C app-eselect/eselect-repository
requires:
- category: "apps"
  name: "nodejs"
  version: ">=0"
