excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- git clone https://github.com/maoschanz/drawing.git
- cd drawing && git checkout 2b477b191da431da49fc82f28ad7760df9f1698e && meson build/ && ninja -C build/
steps:
- cd drawing && ninja -C build/ install
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
