excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 app-eselect/eselect-repository
- eselect repository add mocaccino-overlay git https://codeberg.org/MocaccinoOS/mocaccino-overlay.git
- emaint sync -r mocaccino-overlay
- USE="introspection curl" emerge -1 sys-apps/flatpak sys-apps/fwupd
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
