excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
# Remove BDEPS
- emerge -C sys-devel/lld dev-util/cbindgen net-libs/nodejs
# Moccacino OS customization for bookmarks, start site and bookmarks toolbar.
- cp -rf distribution/distribution.ini /usr/lib64/firefox/distribution/
requires:
- category: "layers"
  name: "X"
  version: ">=0"
- category: "layers"
  name: "net-tools"
  version: ">=0"
