excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- sed -i '/syslog/d' /lib/systemd/system/lightdm.service
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
