includes:
- /etc$
- /etc/env.d$
- /etc/env.d/04gcc-x86_64-pc-linux-gnu
- /etc/ld.so.conf.d$
- /etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- /etc/env.d/gcc$
- /etc/env.d/gcc/.*
- /usr$
- /usr/lib$
- /usr/lib/gcc$
- /usr/lib/gcc/x86_64-pc-linux-gnu$
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}$
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32$
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbegin.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginS.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginT.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtend.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtendS.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtfastmath.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec32.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec64.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec80.o
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_arithmetic.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_exceptions.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_features.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libatomic.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgcc_s.so
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgcc_s.so.1
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgfortran.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgomp.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libquadmath.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libstdc.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crt.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude$
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_arithmetic.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_exceptions.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_features.mod
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libatomic.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgcc_s.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgfortran.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgomp.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libquadmath.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libstdc.*
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_.*
- /usr/lib/llvm$
- /usr/lib/llvm/10$
- /usr/lib/llvm/10/lib64$
- /usr/lib/llvm/10/lib$
- /usr/lib/llvm/.*/lib.*/libLLVM.*.so
- /usr/share$
- /usr/share/gcc-data$
- /usr/share/gcc-data/x86_64-pc-linux-gnu$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info/libgomp.info
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info/libquadmath.info
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de/LC_MESSAGES
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de/LC_MESSAGES/libstdc.*
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr/LC_MESSAGES
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr/LC_MESSAGES/libstdc.*
# Emerge cache files
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
unpack: true
requires:
- name: system-x
  version: ">=0"
  category: layers