env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=on
- CGO_ENABLED=1

prelude:
- mkdir -p ~/.ssh
- ssh-keyscan github.com >> ~/.ssh/known_hosts
- wget https://golang.org/dl/go{{.Values.golang_version}}.linux-{{.Values.arch}}.tar.gz -O golang.tar.gz
- tar -C /usr/local -xzf golang.tar.gz
- go get github.com/rakyll/statik
- | 
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    git clone https://github.com/mocaccinoOS/statusbar.git && cd statusbar && git checkout "${PACKAGE_VERSION}" -b build
steps:
- |
  export PATH=$PATH:$GOPATH/bin && \
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd statusbar && DESTDIR=/statusbar VERSION="${PACKAGE_VERSION}" ./build.sh
package_dir: "/statusbar"
requires:
- category: "layers"
  name: "X"
  version: ">=0"
- name: check-upgrades
  category: system-profile
  version: ">=0"
- name: donate
  category: system-profile
  version: ">=0"