excludes:
{{ template "portage_excludes" }}
- ^/var/lib/module-rebuild
- ^/usr/lib/modules/.*-mocaccino/modules\..*
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
  #prelude:
# Add custom package.use for each package in the collection
#- cp -rf {{.Values.name}}/package.use /etc/portage/
prelude:
{{ if contains "xone" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable src_prepare-overlay
- emaint sync -r src_prepare-overlay
{{- end}}
{{ if contains "rtl8812au" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable rasdark
- emaint sync -r rasdark
{{- end}}
{{ if contains "rtl8192eu" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable guru
- emaint sync -r guru
{{- end}}
{{ if contains "rtl88x2bu" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable sam_c
- emaint sync -r sam_c
{{- end}}
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.unmask /etc/portage/
- emerge -t -o -j ${JOBS} {{ join " " .Values.emerge.packages }}
steps:
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}
{{- if .Values.xone }}
- emerge -C app-eselect/eselect-repository
{{- end}}
{{- if contains "nvidia" .Values.name }}
- |
   mkdir -p /etc/dracut.conf.d/ && \
   cp nvidia-dracut.conf /etc/dracut.conf.d/99-nvidia.conf
{{- end}}
requires:
- category: "kernel-sources"
{{- if .Values.lts }}
  name: "mocaccino-lts-sources"
{{- else}}
  name: "mocaccino-sources"
{{- end}}
  version: ">=0"
