excludes:
{{ template "portage_excludes" }}
- ^/var/lib/module-rebuild
- ^/lib/modules/.*-mocaccino/modules\..*

env:
{{ template "portage_env" . }}
  #prelude:
# Add custom package.use for each package in the collection
#- cp -rf {{.Values.name}}/package.use /etc/portage/
prelude:
{{ if contains "xone" .Values.name }}
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
- echo "y" | layman -a src_prepare-overlay
{{- end}}
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -t -o -j ${JOBS} {{ join " " .Values.emerge.packages }}
steps:
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}
{{- if .Values.xone }}
- emerge -C app-portage/layman dev-python/ssl-fetch
{{- end}}
requires:
- category: "kernel-sources"
{{- if .Values.lts }}
  name: "mocaccino-lts-sources"
{{- else}}
  name: "mocaccino-sources"
{{- end}}
  version: ">=0"
