excludes:
{{ template "portage_excludes" }}
- ^/var/lib/module-rebuild
- ^/lib/modules/.*-mocaccino/modules\..*

env:
{{ template "portage_env" . }}
  #prelude:
# Add custom package.use for each package in the collection
#- cp -rf {{.Values.name}}/package.use /etc/portage/
prelude:
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -t -o -j ${JOBS} {{ join " " .Values.emerge.packages }}

steps:
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}

requires:
- category: "kernel-sources"
{{- if .Values.lts }}
  name: "mocaccino-lts-sources"
{{- else}}
  name: "mocaccino-sources"
{{- end}}
  version: ">=0"